name: Pipeline CI/CD
run-name: Pipeline CI/CD executada por ${{github.actor}} em ${{github.run_number}}

on:
  workflow_dispatch: 
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Obtendo o código do projeto
        uses: actions/checkout@v4

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.300"

      - name: Execução do comando build
        working-directory: ./src
        run: dotnet build Review-Filmes.sln

  testes:
    needs: [build]
    uses: wbm01/desafio-cicd-01/.github/workflows/testes.yml@main

  release:
    needs: [testes]
    name: Criação de Release
    runs-on: ubuntu-latest
    steps:
      - name: Obtendo o código do projeto
        uses: actions/checkout@v4

      - name: Docker Login
        uses: docker/login-action@v3.6.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build e Push da Imagem Docker
        uses: docker/build-push-action@v6
        with:
          context: ./src
          file: ./src/Review-Filmes.Web/Dockerfile
          push: true
          tags: |
            willianmarioti/review-filmes:latest
            willianmarioti/review-filmes:v${{ github.run_number }}